app/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    PasswordField,
    SubmitField,
    StringField,
    BooleanField
)
from flask_login import current_user
from flask_wtf.file import FileField
from wtforms.fields.html5 import EmailField
from wtforms.validators import (
    DataRequired,
    Length,
    EqualTo,
    ValidationError
)

from app import db
from app.models import User


class FamilyProfileUpdateForm(FlaskForm):
    family_picture = FileField(
        'Family picture'
    )


class UserProfileUpdateForm(FlaskForm):
    name = StringField('Username', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    first_name = StringField('First name', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    last_name = StringField('Last name', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    email = EmailField('Email', [
        DataRequired(),
        Length(min=4, max=256),
    ])
    user_picture = FileField(
        'User picture'
    )

    def validate_email(form, field):
        if db.session.query(db.exists().where(
                User.email == field.data.lower())
        ).scalar():
            if current_user.email != field.data.lower():
                raise ValidationError(f'{field.data} is already taken.')

    def validate_name(form, field):
        if db.session.query(db.exists().where(
                User.name_lower == field.data.lower())
        ).scalar():
            if current_user.name_lower != field.data.lower():
                raise ValidationError(f'{field.data} is already taken.')


class NewUserForm(FlaskForm):
    name = StringField('Username', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    first_name = StringField('First name', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    last_name = StringField('Last name', [
        DataRequired(),
        Length(min=4, max=32),
    ])
    email = EmailField('Email', [
        DataRequired(),
        Length(min=4, max=256),
    ])
    password = PasswordField('Password', [
        DataRequired(),
        EqualTo('confirm', message='Passwords must match'),
    ])
    confirm = PasswordField('Repeat Password', [
        DataRequired(),
    ])
    admin = BooleanField(
        'Admin',
        default=True
    )
    user_picture = FileField(
        'User picture'
    )

    def validate_email(form, field):
        if db.session.query(db.exists().where(
                User.email == field.data.lower())
        ).scalar():
            if current_user.email != field.data.lower():
                raise ValidationError(f'{field.data} is already taken.')

    def validate_name(form, field):
        if db.session.query(db.exists().where(
                User.name_lower == field.data.lower())
        ).scalar():
            if current_user.name_lower != field.data.lower():
                raise ValidationError(f'{field.data} is already taken.')


class DeleteUserForm(FlaskForm):
    name = StringField('Username', [
        Length(min=4, max=32),
        DataRequired()
    ])
    submit = SubmitField('Delete')

app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from app.profile import routes

app/profile/routes.py
from flask import (
    render_template,
    request,
    redirect,
    flash,
    current_app,
    url_for,
    abort
)
from flask_login import login_required, current_user

from app import db
from app.models import Family, User, Visit
from .forms import (
    UserProfileUpdateForm,
    FamilyProfileUpdateForm,
    NewUserForm,
    DeleteUserForm
)
from . import bp
from app.utils.dropbox_helpers import (
    upload_user_picture,
    upload_family_picture
)


@bp.route('/me', methods=['GET', 'POST'])
@login_required
def update_user_profile():
    form = UserProfileUpdateForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        file = form.user_picture.data
        upload_user_picture(file, current_user)
        db.session.commit()
        flash('Your profile has been updated!')
    return render_template('profile/edit_user_profile.html', form=form, user_picture=current_user.get_picture_url)


@bp.route('/family', methods=['GET', 'POST'])
@login_required
def family():
    form = FamilyProfileUpdateForm()
    user_family = current_user.family

    if not user_family:
        user_family = Family()
        user_family.users.append(current_user)
        db.session.add(user_family)
        db.session.commit()

    page = request.args.get('page', 1, type=int)
    users = user_family.users.order_by(User.datetime.asc()).paginate(
        page, current_app.config['USER_PER_PAGE'], False)

    next_url = url_for('profile.family', page=users.next_num) \
        if users.has_next else None
    prev_url = url_for('profile.family', page=users.prev_num) \
        if users.has_prev else None

    if form.validate_on_submit():
        file = form.family_picture.data
        if file:
            upload_family_picture(file, user_family)
        db.session.commit()
        flash('Family profile has been updated!')
    return render_template('profile/edit_family_profile.html',
                           form=form,
                           family_picture=user_family.get_picture_url,
                           users=users.items,
                           next_url=next_url,
                           prev_url=prev_url)


@bp.route('/user/add', methods=['GET', 'POST'])
@login_required
def user_add():
    if not current_user.admin:
        abort(404)

    form = NewUserForm()

    if form.validate_on_submit():
        new_user = User(
            name=form.name.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data,
            admin=form.admin.data,
        )
        new_user.family_id = current_user.family_id
        file = form.user_picture.data
        db.session.add(new_user)
        db.session.commit()
        if file:
            upload_user_picture(file, new_user)
        db.session.commit()
        flash('Member has been created!', 'primary')
        return redirect(url_for('profile.family'))
    return render_template('profile/add_new_member.html', form=form)


@bp.route('/user/<uuid:user_id>', methods=['GET'])
@login_required
def user_profile(user_id):
    user = User.query.get_or_404(str(user_id))

    page = request.args.get('page', 1, type=int)
    visits = user.visits.order_by(Visit.visit_date.desc()).paginate(
        page, current_app.config['USER_PER_PAGE'], False)

    next_url = url_for('profile.user_profile', user_id=user_id, page=visits.next_num) \
        if visits.has_next else None
    prev_url = url_for('profile.user_profile', user_id=user_id, page=visits.prev_num) \
        if visits.has_prev else None

    return render_template(
        'profile/user_profile.html',
        user=user,
        visits=visits.items,
        next_url=next_url,
        prev_url=prev_url
    )


@bp.route('/visit', methods=['GET'])
@login_required
def visit_list():
    user_family = current_user.family

    if not user_family:
        user_family = Family()
        user_family.users.append(current_user)
        db.session.add(user_family)
        db.session.commit()

    page = request.args.get('page', 1, type=int)

    visits = user_family.visits.order_by(Visit.visit_date.desc()).paginate(
        page, current_app.config['USER_PER_PAGE'], False)

    next_url = url_for('profile.visit_list', page=visits.next_num) \
        if visits.has_next else None
    prev_url = url_for('profile.visit_list', page=visits.prev_num) \
        if visits.has_prev else None

    return render_template('profile/visit_list.html',
                           page=page,
                           visits=visits.items,
                           next_url=next_url,
                           prev_url=prev_url)


@bp.route('/visit/<uuid:visit_id>', methods=['GET'])
@login_required
def visit_profile(visit_id):
    visit = Visit.query.get_or_404(str(visit_id))
    return render_template('profile/visit_profile.html', visit=visit)


@bp.route('/user/<uuid:user_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    if not current_user.admin:
        abort(404)

    form = DeleteUserForm()
    user = User.query.get_or_404(str(user_id))
    if form.validate_on_submit():
        if user.name == form.name.data:
            db.session.delete(user)
            db.session.commit()
            flash('User has been deleted!', 'primary')
            return redirect(url_for('profile.family'))
        return render_template('profile/delete_user.html', form=form, user=user, error=True)
    return render_template('profile/delete_user.html', form=form, user=user)


@bp.route('/user/unknown', methods=['GET'])
@login_required
def unknown_profile():
    current_family = current_user.family

    page = request.args.get('page', 1, type=int)
    visits = Visit.query.filter_by(user_id=None, family=current_family).\
        order_by(Visit.visit_date.desc()).\
        paginate(page, current_app.config['USER_PER_PAGE'], False)

    next_url = url_for('profile.unknown_profile', page=visits.next_num) \
        if visits.has_next else None
    prev_url = url_for('profile.unknown_profile', page=visits.prev_num) \
        if visits.has_prev else None

    last_visit = Visit.query.filter_by(user_id=None, family=current_family).\
        order_by(Visit.visit_date.desc()).first()

    return render_template(
        'profile/unknown_profile.html',
        last_visit=last_visit,
        visits=visits.items,
        next_url=next_url,
        prev_url=prev_url
    )

app/templates/profile/add_new_member.html
{% extends "base.html" %}
{% block title %}New member | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
   <div class="container">
    <h1>Edit profile</h1>
   </div>
    <form method="post" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <div class="row">
        <div class="col-8">
          <div class="form-group">
            {% if form.name.errors %}
              {{ form.name(class="form-control is-invalid", placeholder="Name") }}
            {% else %}
              {{ form.name(class="form-control", placeholder="Name") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.name.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="form-group">
            {% if form.first_name.errors %}
              {{ form.first_name(class="form-control is-invalid", placeholder="First name") }}
            {% else %}
              {{ form.first_name(class="form-control", placeholder="First name") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.first_name.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="form-group">
            {% if form.last_name.errors %}
              {{ form.last_name(class="form-control is-invalid", placeholder="Last name") }}
            {% else %}
              {{ form.last_name(class="form-control", placeholder="Last name") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.last_name.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="form-group">
            {% if form.email.errors %}
              {{ form.email(class="form-control is-invalid", placeholder="Email") }}
            {% else %}
              {{ form.email(class="form-control", placeholder="Email") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.email.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="form-group">
            {% if form.password.errors %}
              {{ form.password(class="form-control is-invalid", placeholder="Password") }}
            {% else %}
              {{ form.password(class="form-control", placeholder="Password") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.password.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="form-group">
            {% if form.confirm.errors %}
              {{ form.confirm(class="form-control is-invalid", placeholder="Retype password") }}
            {% else %}
              {{ form.confirm(class="form-control", placeholder="Retype password") }}
            {% endif %}
            <div class="invalid-feedback">
              <ul>
                {% for error in form.confirm.errors %}
                  <li>
                    {{ error }}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          <div class="footer">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </div>
        <div class="col-4">
          <div class="form-group">
            <label>Upload Avatar</label>
            <img id='img-upload'/>
            <div class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-light btn-file">
                  Browse...{{ form.user_picture(class="user_picture", id="user_picture") }}
                </span>
              </span>
              <input type="text" class="form-control" readonly>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}
{% block javascript %}
  <script>
    $(document).ready( function() {
        $(document).on('change', '.btn-file :file', function() {
      var input = $(this),
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
      input.trigger('fileselect', [label]);
      });

      $('.btn-file :file').on('fileselect', function(event, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
      function readURL(input) {
          if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                  $('#img-upload').attr('src', e.target.result);
              }

              reader.readAsDataURL(input.files[0]);
          }
      }

      $("#user_picture").change(function(){
          readURL(this);
      });
    });
  </script>
{% endblock %}

app/templates/profile/delete_user.html
{% extends "base.html" %}
{% block title %}Delete member | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
    <form method="post">
      {{ form.csrf_token }}
      <div class="col-md-6">
        <div class="form-group">
          <p>Enter username <b>{{ user.name }}</b></p>
          {% if form.name.errors %}
            {{ form.name(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              <ul>
                <li>
                  <p>Invalid username</p>
                </li>
              </ul>
            </div>
          {% else %}
            {{ form.name(class="form-control") }}
          {% endif %}

        </div>
        <div class='form-group'>
          {{ form.submit(class="btn btn-danger") }}
        </div>
      </div>
    </form>
  </div>
{% endblock %}

app/templates/profile/edit_family_profile.html
{% extends "base.html" %}
{% block title %}Family | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="animated fadeOut slower">
          <div class="alert-top alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
          </div>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="container">
    <div class="container">
      <h1>Family profile</h1>
    </div>

    <div class="row">
      <div class="col-8">
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Full name</th>
                <th scope="col">Last visit</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for user in users %}
                <tr>
                  <td>{{ loop.index }}</td>
                  <td>{{ user.full_name }}</td>
                  {% if user.last_visit %}
                    <td>{{ moment(user.last_visit.visit_date).format('MMMM Do, h:mm:ss a') }}</td>
                  {% else %}
                    <td>None</td>
                  {% endif %}
                  <td>
                    <a class="btn btn-primary" href="{{ url_for('profile.user_profile', user_id=user.id) }}">View</a>
                  </td>
                  <td>
                    {% if current_user.admin and current_user.id != user.id %}
                      <a class="btn btn-danger" href="{{ url_for('profile.delete_user', user_id=user.id) }}">Delete</a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="row">
          {% if prev_url %}
            <a href="{{ prev_url }}">Last</a>
          {% endif %}
          {% if next_url %}
            <a href="{{ next_url }}">Next</a>
          {% endif %}
        </div>
        {% if current_user.admin %}
          <div class="row">
            <a class="btn btn-primary" href="{{ url_for('profile.user_add') }}">Add new member</a>
          </div>
        {% endif %}

      </div>
      <div class="col-4">
        <form method="post" enctype="multipart/form-data">
          {{ form.csrf_token }}
          <div class="form-group">
            <label>Family picture</label>
          </div>
          <div class="form-group">
            {% if family_picture %}
              <img id='img-upload' src="{{ family_picture }}"/>
            {% else %}
              <img id='img-upload' src="{{ url_for('static', filename='img/family_defult.jpg') }}"/>
            {% endif %}
            <div class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-light btn-file">
                  Browse...{{ form.family_picture(class="family_picture", id="family_picture") }}
                </span>
              </span>
              <input type="text" class="form-control" readonly>
            </div>
          </div>
          <div class="form-group">
            <div class="footer">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block javascript %}
  <script>
    $(document).ready( function() {
        $(document).on('change', '.btn-file :file', function() {
      var input = $(this),
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
      input.trigger('fileselect', [label]);
      });

      $('.btn-file :file').on('fileselect', function(event, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
      function readURL(input) {
          if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                  $('#img-upload').attr('src', e.target.result);
              }

              reader.readAsDataURL(input.files[0]);
          }
      }

      $("#family_picture").change(function(){
          readURL(this);
      });
    });
  </script>
{% endblock %}

app/templates/profile/unknown_profile.html
{% extends "base.html" %}
{% block title %}Unknown | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
    <div class="container">
      <h1>Unknown user visits</h1>
    </div>
    <div class="row justify-content-center">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><b>Last visit: </b>{{ moment(last_visit.visit_date).format('MMMM Do, h:mm:ss a') }}</h5>
            <img src="{{ last_visit.get_picture_url }}" alt="">
          </div>
          <div class="card-footer">
            <div class="row">
              <div class="container">
                <h2 class="card-title">Visit list</h2>
              </div>
            </div>
            <div class="row">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Full name</th>
                    <th scope="col">Visiting time</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for visit in visits %}
                    <tr>
                      <td>Unknown</td>
                      <td>{{ moment(visit.visit_date).format('MMMM Do, h:mm:ss a') }}</td>
                      <td>
                        <a class="btn btn-primary" href="{{ url_for('profile.visit_profile', visit_id=visit.id) }}">View</a>
                      </td>
                    </tr>
                  {% else %}
                    <td colspan="3">None</td>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="row justify-content-between">
              <div class="col-4">
                {% if prev_url %}
                  <a class="btn btn-outline-primary" href="{{ prev_url }}">Prev</a>
                {% endif %}
              </div>
              <div class="col-4 text-right">
                {% if next_url %}
                  <a class="btn btn-outline-primary" href="{{ next_url }}">Next</a>
                {% endif %}
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/profile/user_profile.html
{% extends "base.html" %}
{% block title %}{{ user.full_name }} | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
    <div class="container">
      <h1>User profile</h1>
    </div>
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          {% if user.get_picture_url %}
            <img id='img-upload' src="{{ user.get_picture_url }}"/>
          {% else %}
            <img id='img-upload' src="{{ url_for('static', filename='img/user_defult.png') }}"/>
          {% endif %}
        </div>
      </div>

      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">{{ user.name }}</h3>
            <p class="card-text">Full name: {{ user.full_name }}</p>
          </div>
          <div class="card-footer">
            {% if user.last_visit.visit_date %}
              <p class="card-text">Last visit: {{ moment(user.last_visit.visit_date).format('MMMM Do, h:mm:ss a') }}</p>
              <img src="{{ user.last_visit.get_picture_url }}" alt="">
              <div>
                <hr>
                <h1 id="visitList" class="">Visit list</h1>
                <div class="row">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Full name</th>
                        <th scope="col">Visiting time</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for visit in visits %}
                        <tr>
                          <td>{{ visit.user.full_name }}</td>
                          <td>{{ moment(visit.visit_date).format('MMMM Do, h:mm:ss a') }}</td>
                          <td>
                            <a class="btn btn-primary" href="{{ url_for('profile.visit_profile', visit_id=visit.id) }}">View</a>
                          </td>
                        </tr>
                      {% else %}
                        <td colspan="3">None</td>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="row justify-content-between">
                  <div class="col-4">
                    {% if prev_url %}
                      <a class="btn btn-outline-primary" href="{{ prev_url }}#visitList">Prev</a>
                    {% endif %}
                  </div>
                  <div class="col-4 text-right">
                    {% if next_url %}
                      <a class="btn btn-outline-primary" href="{{ next_url }}#visitList">Next</a>
                    {% endif %}
                  </div>
                </div>

              </div>
            {% else %}
              <p class="card-text">Last visit: None</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/profile/visit_list.html
{% extends "base.html" %}
{% block title %}Visit list | Identifier{% endblock %}

{% block css_link  %}
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
  <div class="newVisit" style="display: none;">
    <div class="animated pulse fast">
      <div class="alert-top alert alert-warning alert-dismissible fade show" role="alert">
        <div>
          <h4><span class="newVisit"></span></h4>
          <strong><a href="{{ url_for('profile.visit_list') }}">Reload</a></strong>
            <button type="button" class="close" aria-label="Close" onclick="hideAlert()">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
      </div>
    </div>
  </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="animated fadeOut slower">
            <div class="alert-top alert alert-{{ category }} alert-dismissible fade show" role="alert">
              {{ message }}
            </div>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="justify-content-center">
      <h1 id="visitList" class="">Visit list</h1>
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Full name</th>
              <th scope="col">Visiting time</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for visit in visits %}
              <tr>
              {% if visit.is_unknown %}
                <td>{{ visit.user.full_name }}</td>
                <td>{{ moment(visit.visit_date).format('MMMM Do, h:mm:ss a') }}</td>
                <td>
                  <a class="btn btn-primary" href="{{ url_for('profile.visit_profile', visit_id=visit.id) }}">View</a>
                </td>
              {% else %}
                <td>Unknown</td>
                <td>{{ moment(visit.visit_date).format('MMMM Do, h:mm:ss a') }}</td>
                <td>
                  <a class="btn btn-primary" href="{{ url_for('profile.visit_profile', visit_id=visit.id) }}">View</a>
                </td>
              {% endif %}
              </tr>
            {% else %}
              <td colspan="3">None</td>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="row justify-content-between">
        <div class="col-4">
          {% if prev_url %}
            <a class="btn btn-outline-primary" href="{{ prev_url }}#visitList">Prev</a>
          {% endif %}
        </div>
        <div class="col-4 text-right">
          {% if next_url %}
            <a class="btn btn-outline-primary" href="{{ next_url }}#visitList">Next</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block javascript %}
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
  <script type="text/javascript" charset="utf-8">
    var socket;
    var dt = new Date();
    $(document).ready(function(){
      console.log("---here---");
      socket = io.connect('http://' + document.domain + ':' + location.port + '/visit');
      socket.on('new_visit', function(data) {
        console.log(data);
        $("span.newVisit").html("New visiter: " + data.user + " " + data.datetime);
        $("div.newVisit").show();
      });
    });
    function hideAlert() {
      $("div.newVisit").hide();
    }
  </script>
{% endblock %}

app/templates/profile/visit_profile.html
{% extends "base.html" %}
{% block title %} Visit | Identifier{% endblock %}

{% block css_link  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/registration.css') }}">
{% endblock %}

{% block content %}
  {% include 'header.html' %}
  <div class="container">
    <div class="container">
      <h1>Visit profile</h1>
    </div>
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          <img id='img-upload' src="{{ visit.get_picture_url }}" alt="Visit photo"/>
        </div>
      </div>

      <div class="col-8">
        <div class="card">
          <div class="card-body">
            {% if visit.is_unknown %}
              <h3 class="card-title">Who: <a href="{{ url_for('profile.user_profile', user_id=visit.user_id) }}">{{ visit.user.full_name }}</a></h3>
            {% else %}
              <h3 class="card-title">Who: <a href="{{ url_for('profile.unknown_profile') }}">Unknown</a></h3>
            {% endif %}
          </div>
          <div class="card-footer">
            <p class="card-text">Visiting time: {{ moment(visit.visit_date).format('MMMM Do, h:mm:ss a') }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}